FROM ubuntu:22.04

LABEL author="Yogi"


RUN apt update 
RUN apt install openjdk-8-jre-headless -y
#RUN apt install mysql-client-core-8.0 -y


ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz /opt/
RUN tar -xvf /opt/apache-tomcat-8.5.99.tar.gz -C /opt

EXPOSE 8080

WORKDIR /opt/apache-tomcat-8.5.99

ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war webapps/

ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar lib/

ADD context.xml conf/context.xml




CMD bin/catalina.sh run


