apiVersion: v1
kind: Pod
metadata:
  name: my-pod-object
  labels:
    app: my-pod-1
  namespace: ns-demo
spec:
  containers:
    - name: my-pod
      image: httpd
      ports:
        - containerPort: 80
