FROM ubuntu:latest

    LABEL Author="Admin"
    
    USER root

    RUN apt update -y

    RUN apt install apache2 -y
    RUN apt install php -y
    RUN apt install php libapache2-mod-php php-mysql -y
    RUN apt install wordpress -y

    ADD sudo wget https://en-au.wordpress.org/latest-en_AU.tar.gz /tmp/
    WORKDIR /tmp/
    RUN sudo tar -xvf latest-en_AU.tar.gz
    WORKDIR /tmp/wordpress /root/var/www/html
    RUN sudo systemctl restart apache2
    
    
    EXPOSE 8080
