---
- name: Install Apache
  hosts: webservers # Replace with your target hosts
  become: True
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Download myfile.zip
      get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page291/hightech.zip
        dest: /home/ubuntu
        mode: 0666
    - name: Install unzip package
      apt:
        name: unzip
        state: present
        update_cache: yes
    - name: Unzip file
      unarchive:
        src: /home/ubuntu/hightech.zip
        dest: /home/ubuntu/
        remote_src: True
        owner: ubuntu
        group: ubuntu
    - name: Rename folder with shell module
      shell: mv /home/ubuntu/hightech-html /home/ubuntu/html
      become: True 
    - name: Move file with copy module
      copy:
        src: /home/ubuntu/html
        dest: /var/www/
        remote_src: True
        owner: ubuntu
        group: ubuntu
        mode: '0666'