FROM ubuntu:latest

    LABEL Author="Yogesh"
    
    USER root

    RUN apt update -y

    RUN apt install apache2 -y
    RUN apt install php -y
    RUN apt install php libapache2-mod-php php-mysql -y
    RUN apt install wordpress -y

    ADD sudo wget https://en-au.wordpress.org/latest-en_AU.tar.gz /tmp/
    WORKDIR /tmp/
    RUN sudo tar -xvf latest-en_AU.tar.gz
    WORKDIR /tmp/wordpress /root/var/www/html
    
    ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz /opt/
    
    
    RUN tar -xvf /opt/apache-tomcat-8.5.99.tar.gz -C /opt/
    
    
    EXPOSE 8080
